### PR TITLE
fix: use  `response._bodyInit` as fallback for react-native and qq

### LINKED ISSUE #324: `undefined` responses when used with React Native
### Environment

React Native (all versions)

### Reproduction

It is difficult to provide a react-native starter as I'm not a specialist, and it will require that you install and setup everything to start a react-native project. Instead, you could rely on my detailed investigation

### Describe the bug

Hi,

in the light of [this issue](https://github.com/unjs/ofetch/issues/293),

Looking deeper into the commit linked by @pi0 to close the issue, and having the same issue as @gtjamesa (responses are all `undefined`), it seems that this commit will not fix the `undefined` responses issue.

I dug into `ofetch` source code and did my own investigation. It appears that there is a boolean `hasBody` which checks if `response.body` exists, [as expected in fetch Response spec](https://developer.mozilla.org/en-US/docs/Web/API/Response), see: https://github.com/unjs/ofetch/blob/bb2d72baa5d3f332a2185c20fc04e35d2c3e258d/src/fetch.ts#L172-L173

Yet, only these fields are available in the `response` object returned by `fetch` in React Native:
`_bodyBlob`, `_bodyInit`, `bodyUsed`, `headers`, `status`, `statusText`, `type`.

Indeed, react-native [uses](https://github.com/facebook/react-native/commit/bccc92dfdd2d85933f2a9cb5c8d1773affb7acba) [whatwg-fetch polyfill](https://github.com/JakeChampion/fetch).

We can easily see [in whatwg-fetch source code](https://github.com/JakeChampion/fetch/blob/main/fetch.js) that all these keys are defined by the polyfill on `this`, but **not** `body`.

The correct answer would be to create an issue on `whatwg-fetch` so that they update their code and comply with Fetch API, and then create an issue on React Native to use this updated library, and then update React Native. Nevertheless, this process can take a while, and (as it is the case for our projects) many React Native projects are stuck to older versions because they depend on other libs that breaks and haven't updated yet and an update to the latest is very difficult.

The shorter answer would be to adapt `ofetch` so that it also checks specific `whatwg-fetch` fields in the response to know if a body is available.

What do you think ?

### Additional context

_No response_

### Logs

_No response_

### PR DESCRIPTION
**Pull request by joshmossas**
### 🔗 Linked issue

Fixes #324 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This pr is essentially a one line change to add react native support. It checks `response._bodyInit` in addition to `response.body` to see if a body exists in the response.

Normally I would say that this is an upstream issue that react native should fix, but the reality is fetch has not been spec compliant in react native for a long time, and it doesn't seem like there has been any meaningful progress in that department either. So I don't think it's practical to wait on them. 

I would also argue that even though this is a runtime specific check it shouldn't add any overhead for maintainers because its such a small change. I've also included comments explaining what the additional `_bodyInit` check is for and under what conditions it can be removed.

Additionally this repo does have a precedent for runtime specific check. In `./src/fetch.ts` line 84, there is a check for a chromium specific API. So this change would be in line with that.
https://github.com/unjs/ofetch/blob/f7f946395544f3ab39fd2e5c61110b5371d7e9dd/src/fetch.ts#L84

In all I think this is a worthwhile change as it would let users use the same fetch library across, node, browsers, and react native.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: src/fetch.ts [hunk 1]
```diff
@@ -194,7 +194,9 @@ export function createFetch(globalOptions: CreateFetchOptions = {}): $Fetch {
     }
 
     const hasBody =
-      context.response.body &&
+      (context.response.body ||
+        // https://github.com/JakeChampion/fetch/issues/1454
+        (context.response as any)._bodyInit) &&
```
Comment (pi0) [inline src/fetch.ts:199]: We need to handle this line now since there is a second source:

https://github.com/joshmossas/ofetch/blob/e11a6a0ca98196c239bd3f65c92be847abdc6898/src/fetch.ts

Comment (joshmossas) [reply src/fetch.ts:199]: @pi0 Okay I can make a quick patch

Comment (joshmossas) [reply src/fetch.ts:199]: Although I should mention, that streams still don't work properly on react native so idk if this is actually necessary.

Their fetch implementation is kinda jank lol

Comment (joshmossas) [reply src/fetch.ts:199]: Sure I can check real quick

**Review by pi0 — APPROVED** [review]

File: src/fetch.ts (hunk 1 above)
Comment (pi0) [reply src/fetch.ts:201]: Thanks! Merging in between feel free to amend method if had any new findings.

**Comment by joshmossas** [comment]
@pi0 so I just checked with React Native running on my android phone

When `responseType` is set to `"stream"` the `_bodyInit` is an instance of `Blob`. However it doesn't implement any of the methods specified in the [Web standard](https://developer.mozilla.org/en-US/docs/Web/API/Blob) such as `_bodyInit.stream()` or `_bodyInit.text()`. It only implements the following interface:

```ts
interface Blob {
  readonly size: number;
  readonly type: string;
  slice(start?: number, end?: number, contentType?: string): Blob;
}
```

So none of the standard methods are present. As far as I can tell there's no way to get the actual data out of it.

**Comment by joshmossas** [comment]
Additionally logging the _bodyInit to the console outputs the following:
```ts
{"_data": {"__collector": {}, "blobId": "244dfb46-0c73-45f8-99be-cfd8b2bb971f", "offset": 0, "size": 1256}}
```

When normally logging a Blob would look like this:
```ts
Blob { size: 11, type: '' }
```

**Comment by pi0** [comment]
I see, basically seems stream mode is broken. 

Although now other types (text/json) work right?

**Comment by joshmossas** [comment]
Yes I had no problem getting text and json to work
